# --------------------------------------
# User config
# --------------------------------------
title:              낮코밤코

email:              owin2828@gmail.com
description:        Already done, cause will do it anyway
author:             owin2828
baseurl:            ""

# The unique resource location
url:                "https://owin2828.github.io"

navtitle:           Fake it, till U make it              

# Social Profiles
twitter_username:  
github_username:    owin2828
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-154694140-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# --------------------------------------
# Collection
# --------------------------------------
collections:
  featured_categories:
    permalink:       /category/:name/
    output:          true
  featured_tags:
    permalink:       /tag/:name/
    output:          true